version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: '09:00'
      timezone: Asia/Colombo
    open-pull-requests-limit: 1
    groups:
      frontend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: '09:00'
      timezone: Asia/Colombo
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - '*'
